# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.8

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
install:
  - pipenv install --dev --ignore-pipfile --deploy

before_script: # code coverage tool
   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
   - chmod +x ./cc-test-reporter
   - ./cc-test-reporter before-build
script:
  - pytest --cov-report xml --cov-report term
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  # Before running, get the data from s3 using the secret
  # credentials entered at https://travis-ci.com/csci-e-29/YOUR_PSET_REPO_NAME/settings
  # DO NOT commit these variables to git.
  script: pipenv run python -m pset_4


